directories:
  datadir: /scratch/drt83172/Wallace_lab/RNA_SEQ/Data
  scriptdir: /scratch/drt83172/Wallace_lab/RNA_SEQ/Scripts
  qcdir: /scratch/drt83172/Wallace_lab/RNA_SEQ/qc
  logs: /scratch/drt83172/Wallace_lab/RNA_SEQ/logs
  mqcdir: /scratch/drt83172/Wallace_lab/RNA_SEQ/mqcdir
  trimmed: /scratch/drt83172/Wallace_lab/RNA_SEQ/Trimmed
  genome_idx: /scratch/drt83172/Wallace_lab/RNA_SEQ/Genome_idx
  align: /scratch/drt83172/Wallace_lab/RNA_SEQ/Alignment
  star_bams: /scratch/drt83172/Wallace_lab/RNA_SEQ/star_bams/
  sep_bams: /scratch/drt83172/Wallace_lab/RNA_SEQ/sep_bams/
  features: /scratch/drt83172/Wallace_lab/RNA_SEQ/features/
  log: /scratch/drt83172/Wallace_lab/RNA_SEQ/log
  transcriptome_dir: /scratch/drt83172/Wallace_lab/RNA_SEQ/transcriptome
  transdecoder_dir: /scratch/drt83172/Wallace_lab/RNA_SEQ/transcriptome/predicted_transcripts.fasta.transdecoder_dir

lists:
  paired_list_file: /scratch/drt83172/Wallace_lab/RNA_SEQ/Scripts/RNA_seq_fescue/paired_list.txt

genome: /scratch/drt83172/Wallace_lab/RNA_SEQ/Genome/tall_fescuev0.1.fa
star_manifest: manifest.tsv

params:
  star_mapping:
    log: /scratch/drt83172/Wallace_lab/RNA_SEQ/log/samtoolsview_log.txt
    threads: 32
    threads_multi: 10

scallop:
  output_file: /scratch/drt83172/Wallace_lab/RNA_SEQ/transcriptome/Fescue_transcriptome_mini.gtf



star_index_files:
    - "SA"
    - "SAindex"
    - "Genome"
    - "chrLength.txt"
    - "chrName.txt"
    - "chrNameLength.txt"
    - "chrStart.txt"
    - "genomeParameters.txt"

use_ignored_rule: false

bedtools:
  fasta_output: /scratch/drt83172/Wallace_lab/RNA_SEQ/transcriptome/predicted_transcripts.fasta

interproscan:
  tsv_output: /scratch/drt83172/Wallace_lab/RNA_SEQ/transcriptome/interproscan_results.tsv

transdecoder:
  gff3: /scratch/drt83172/Wallace_lab/RNA_SEQ/transcriptome/transcripts.gff3
  long_orfs: /scratch/drt83172/Wallace_lab/RNA_SEQ/transcriptome/predicted_transcripts.fasta.transdecoder_dir/longest_orfs.pep
  pep: /scratch/drt83172/Wallace_lab/RNA_SEQ/transcriptome/predicted_transcripts.fasta.transdecoder_dir/predicted_transcripts.fasta.transdecoder.pep
  fasta_gff3: /scratch/drt83172/Wallace_lab/RNA_SEQ/transcriptome/predicted_transcripts.fasta.transdecoder_dir/predicted_transcripts.fasta.transdecoder.gff3
  genome_gff3: /scratch/drt83172/Wallace_lab/RNA_SEQ/transcriptome/predicted_transcripts.fasta.transdecoder_dir/transcripts.fasta.transdecoder.genome.gff3

blast:
    output: /scratch/drt83172/Wallace_lab/RNA_SEQ/Blast/blast_results.txt
    params:
        db: "nr"
        evalue: 1e-5
        outfmt: 6
        num_threads: 24