directories:
  datadir: /scratch/drt83172/Wallace_lab/RNA_SEQ/Data
  scriptdir: /scratch/drt83172/Wallace_lab/RNA_SEQ/Scripts
  qcdir: /scratch/drt83172/Wallace_lab/RNA_SEQ/qc
  logs: /scratch/drt83172/Wallace_lab/RNA_SEQ/logs
  mqcdir: /scratch/drt83172/Wallace_lab/RNA_SEQ/mqcdir
  trimmed: /scratch/drt83172/Wallace_lab/RNA_SEQ/Trimmed
  genome_idx: /scratch/drt83172/Wallace_lab/RNA_SEQ/Genome_idx
  align: /scratch/drt83172/Wallace_lab/RNA_SEQ/Alignment
  star_bams: /scratch/drt83172/Wallace_lab/RNA_SEQ/star_bams

genome: /scratch/drt83172/Wallace_lab/RNA_SEQ/Genome/tall_fescuev0.1.fa
star_manifest: manifest.tsv

params:
  star_mapping:
    threads: 10

scallop:
  output_file: /scratch/drt83172/Wallace_lab/RNA_SEQ/transcriptome/Fescue_transcriptome.gtf