directories:
  datadir: /scratch/drt83172/Wallace_lab/RNA_SEQ/Data
  scriptdir: /scratch/drt83172/Wallace_lab/RNA_SEQ/Scripts
  qcdir: /scratch/drt83172/Wallace_lab/RNA_SEQ/qc
  logs: /scratch/drt83172/Wallace_lab/RNA_SEQ/logs
  mqcdir: /scratch/drt83172/Wallace_lab/RNA_SEQ/mqcdir
  trimmed: /scratch/drt83172/Wallace_lab/RNA_SEQ/Trimmed
  genome_idx: /scratch/drt83172/Wallace_lab/RNA_SEQ/Genome_idx
  align: /scratch/drt83172/Wallace_lab/RNA_SEQ/Alignment
  star_bams: /scratch/drt83172/Wallace_lab/RNA_SEQ/star_bams/
  sep_bams: /scratch/drt83172/Wallace_lab/RNA_SEQ/sep_bams/
  features: /scratch/drt83172/Wallace_lab/RNA_SEQ/features/

lists:
  paired_list_file: /scratch/drt83172/Wallace_lab/RNA_SEQ/Scripts/RNA_seq_fescue/paired_list.txt
  
genome: /scratch/drt83172/Wallace_lab/RNA_SEQ/Genome/tall_fescuev0.1.fa
star_manifest: manifest.tsv

params:
  star_mapping:
    threads: 10

scallop:
  output_file: /scratch/drt83172/Wallace_lab/RNA_SEQ/transcriptome/Fescue_transcriptome.gtf



star_index_files:
    - "SA"
    - "SAindex"
    - "Genome"
    - "chrLength.txt"
    - "chrName.txt"
    - "chrNameLength.txt"
    - "chrStart.txt"
    - "genomeParameters.txt"
